project_id = "harckavibhmimndfvnyo"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sync-abandoned-cart]
verify_jwt = false

[functions.recover-cart]
verify_jwt = false

[functions.process-abandoned-carts]
verify_jwt = false
